In [1]:
"""
Demo of np.where()
"""

In [ ]:
import numpy as np

In [10]:
a=np.array([4,33,3,28,3,41,6,80,10])

In [15]:
#Returns the index where the cell's values is greater than 30 
np.where(a>30)

(array([1, 5, 7]),)

In [17]:
#Updates to zero where the cell's values is greater than 30 
np.where(a>30,a,0)

array([ 0, 33,  0,  0,  0, 41,  0, 80,  0])

In [23]:
#Sums 1000 where the cell's values is greater than 30, if not subtract 1000 
np.where(a>30,a-1000,a+1000)

array([1004, -967, 1003, 1028, 1003, -959, 1006, -920, 1010])

In [22]:
#Updates to 0 the cell when its value is greater than 30, else update to 1 
np.where(a>30,0,1)

array([1, 0, 1, 1, 1, 0, 1, 0, 1])